<?php
/**
 * Implements hook_menu
 */
function ws_villages_menu(){
	$items = array();
	$items['villagelist'] = array(
		'title' => 'Деревни',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'ws_villages_page',
		'access arguments' => array('access content'),
	);
	return $items;
}

/**
 * Generate page
 */
function ws_villages_page(){
	$class_map = array();
	$class_map[0] = 'bg-green-accent-1';
	$class_map[1] = 'bg-red-accent-5';
	$class_map[2] = 'bg-red-accent-2';
	$class_map[3] = 'bg-green-accent-2';
	$class_map[4] = 'bg-purple-accent-1';
	$class_map[5] = 'bg-purple-accent-4';
	$class_map[6] = 'bg-cyan-accent-1';
	$class_map[7] = 'bg-brown-accent-4';
	$class_map[8] = 'bg-brown-accent-3';
	$class_map[9] = 'bg-green-accent-4';
	$class_map[10] = 'bg-cyan-accent-2';
	$class_map[11] = 'bg-green-accent-2';
	$class_map[12] = 'bg-orange-accent-2';
	$class_map[13] = 'bg-red-accent-3';
	$class_map[14] = 'bg-grey-accent-1';
	$class_map[15] = 'bg-brown-accent-5';
	$class_map[16] = 'bg-orange-accent-1';
	$class_map[17] = 'bg-blue-accent-1';
	$class_map[18] = 'bg-red-accent-1';
	$class_map[19] = 'bg-red-accent-4';
	$class_map[20] = 'bg-brown-accent-1';
	$class_map[21] = 'bg-yellow-accent-1';
	$class_map[22] = 'bg-brown-accent-2';
	$class_map[23] = 'bg-purple-accent-3';
	$class_map[24] = 'bg-purple-accent-2';
	$output = '';
	$output .= '<div class="v-grid-template clearfix">';
//left pane
	$output .= '<div class="v-grid-template__list-img" style="background-image: url(sites/default/files/img/img1.jpg);">
            <nav class="village-pagin-nav">
                <ul>
                    <li><a href="#">Генплан</a></li>
                    <li><a href="#">Коммуникации</a></li>
                    <li><a href="#">Документы</a></li>
                </ul>
            </nav>
        </div>';
//right pane
	$output .= '  <div class="v-grid-template__content">
            <div class="v-grid-template__wrap">';
			$crumb = drupal_get_breadcrumb();
	$output .= '<nav class="village-nav">
                    <ul>
                        <li>'.$crumb[0].'</li>
                    </ul>
                </nav>';
	$output	.= '<div class="text-center village-logo">
                    <img src="sites/default/files/img/village-logo/list_logo.png" alt="">
                    <div class="h1">ДЕРЕВНИ</div>
                </div>';
	$output .= '<div class="pure-g">';
	$terms = taxonomy_get_tree(2);
	$i = 0;
	foreach($terms as $term){		
		$output .= '<div class="pure-u-1-4 category-list">';
		$output .= '<div class="title">' . $term->name . '</div>';
		$nids = taxonomy_select_nodes($term->tid);
		if(!empty($nids)) {
			$output .= '<ul>';
		$nodes = node_load_multiple($nids);
			foreach($nodes as $node){
				$output .= '<li><span class="'.$class_map[$i].'"></span>'. l($node->title, drupal_get_path_alias('node/'. $node->nid)) . '</li>';
				$i++;
			}
			$output .= '</ul>';
		}
		$output .= '</div>';
	}
	$output .= '</div></div></div>';
	return $output;
} 

function ws_villages_bread(){ 
	$trail = menu_get_active_trail(); 
	$crumbs = drupal_get_breadcrumb();
	//Get submenu
	$terms = taxonomy_get_tree(2);	
	$output = '<ul class="submenu">';
	foreach($terms as $term){		
		
		$output .= '<li>' . l($term->name, '/villages/' . drupal_get_path_alias('taxonomy/term/'. $term->tid));
		$nids = taxonomy_select_nodes($term->tid);
		if(!empty($nids)) {
			$output .= '<ul class="submenu">';
		$nodes = node_load_multiple($nids);
			foreach($nodes as $node){
				$output .= '<li>'. l($node->title, drupal_get_path_alias('node/'. $node->nid)) . '</li>';				
			}
			$output .= '</ul>';
		}
		$output .= '</li>';
	}
	$output .= '</ul>';
	$i = 0;
	foreach($crumbs as $crumb){
		if(isset($trail[$i]['path'])){ 
			if($trail[$i]['path'] == 'villages/%'){
				$crumbs[$i] .= $output;
			}
		}
		$i++;
	}
	return $crumbs;
}