<?php
/**
 * Implements hook_menu
 */
function ws_villages_menu(){
	$items = array();
	$items['villagelist'] = array(
		'title' => 'Деревни',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'ws_villages_page',
		'access arguments' => array('access content'),
	);
	return $items;
}

/**
 * Generate page
 */
function ws_villages_page(){
	$class_map = array();
	$class_map[0] = 'bg-green-accent-1';
	$class_map[1] = 'bg-red-accent-5';
	$class_map[2] = 'bg-red-accent-2';
	$class_map[3] = 'bg-green-accent-2';
	$class_map[4] = 'bg-purple-accent-1';
	$class_map[5] = 'bg-purple-accent-4';
	$class_map[6] = 'bg-cyan-accent-1';
	$class_map[7] = 'bg-brown-accent-4';
	$class_map[8] = 'bg-brown-accent-3';
	$class_map[9] = 'bg-green-accent-4';
	$class_map[10] = 'bg-cyan-accent-2';
	$class_map[11] = 'bg-green-accent-2';
	$class_map[12] = 'bg-orange-accent-2';
	$class_map[13] = 'bg-red-accent-3';
	$class_map[14] = 'bg-grey-accent-1';
	$class_map[15] = 'bg-brown-accent-5';
	$class_map[16] = 'bg-orange-accent-1';
	$class_map[17] = 'bg-blue-accent-1';
	$class_map[18] = 'bg-red-accent-1';
	$class_map[19] = 'bg-red-accent-4';
	$class_map[20] = 'bg-brown-accent-1';
	$class_map[21] = 'bg-yellow-accent-1';
	$class_map[22] = 'bg-brown-accent-2';
	$class_map[23] = 'bg-purple-accent-3';
	$class_map[24] = 'bg-purple-accent-2';
	$output = '';
	$output .= '<div class="v-grid-template clearfix">';
//left pane
	$output .= '<div class="v-grid-template__list-img" style="background-image: url(sites/default/files/img/img1.jpg);">
            <nav class="village-pagin-nav">
                <ul>
                    <li><a href="#">Генплан</a></li>
                    <li><a href="#">Коммуникации</a></li>
                    <li><a href="#">Документы</a></li>
                </ul>
            </nav>
        </div>';
//right pane
	$output .= '  <div class="v-grid-template__content">
            <div class="v-grid-template__wrap">';
			$crumb = drupal_get_breadcrumb();
	$output .= '<nav class="village-nav">
                    <ul>
                        <li>'.$crumb[0].'</li>
                    </ul>
                </nav>';
	$output	.= '<div class="text-center village-logo">
                    <img src="sites/default/files/img/village-logo/list_logo.png" alt="">
                    <div class="h1">ДЕРЕВНИ</div>
                </div>';
	$output .= '<div class="pure-g">';
	$terms = taxonomy_get_tree(2);
	$i = 0;
	foreach($terms as $term){		
		$output .= '<div class="pure-u-1-4 category-list">';
		$output .= '<div class="title">' . $term->name . '</div>';
		$nids = taxonomy_select_nodes($term->tid);
		if(!empty($nids)) {
			$output .= '<ul>';
		$nodes = node_load_multiple($nids);
			foreach($nodes as $node){
				$output .= '<li><span class="'.$class_map[$i].'"></span>'. l($node->title, drupal_get_path_alias('node/'. $node->nid)) . '</li>';
				$i++;
			}
			$output .= '</ul>';
		}
		$output .= '</div>';
	}
	$output .= '</div></div></div>';
	return $output;
} 

function ws_villages_bread(){ 
	$trail = menu_get_active_trail(); //var_dump($trail);
	$crumbs = drupal_get_breadcrumb(); //var_dump($crumbs);
	//Get submenu
	$terms = taxonomy_get_tree(2);	
	$output = '<ul class="submenu sf-menu">';
	foreach($terms as $term){		
		
		$output .= '<li>' . l($term->name, '/villages/' . drupal_get_path_alias('taxonomy/term/'. $term->tid));
		$nids = taxonomy_select_nodes($term->tid);
		if(!empty($nids)) {
			$output .= '<ul class="submenu sf-menu">';
		$nodes = node_load_multiple($nids);
			foreach($nodes as $node){
				$output .= '<li>'. l($node->title, drupal_get_path_alias('node/'. $node->nid)) . '</li>';				
			}
			$output .= '</ul>';
		}
		$output .= '</li>';
	}
	$output .= '</ul>';	
		if(isset($trail[1]['path'])){ 			
			if($trail[1]['path'] == 'villages/%'){
				$crumbs[1] .= $output;
				if($trail[1]['href'] != 'villages/all'){
					$hr = explode('/',$trail[1]['href']);
					$url = drupal_lookup_path('source', $hr[1]);
					$term_base_path = 'taxonomy/term/';
					if (strncmp($term_base_path, $url, strlen($term_base_path)) == 0)
					{					
						$current_tid = intval(str_replace($term_base_path, '', $url));
						$current_term = taxonomy_term_load($current_tid);
						$nids = taxonomy_select_nodes($current_term->tid, $pager = FALSE, $limit = FALSE, $order=array('t.created' => 'ASC',));
						if(!empty($nids)) {
							$out = '<ul class="villcat submenu sf-menu">';
						$nodes = node_load_multiple($nids);
							foreach($nodes as $node){
								$out .= '<li>'. l($node->title, drupal_get_path_alias('node/'. $node->nid)) . '</li>';				
							}
							$out .= '</ul>';
						}
						$crumbs[] = l($current_term->name, $trail[1]['href']) . $out;
					}
				}
			}
		}
		$cond = false;
		if(isset($trail[1]['router_path'])){
			if($trail[1]['router_path'] == 'node/%') $cond = true;
		}
		if(isset($trail[1]['path'])){
			if($trail[1]['path'] == 'geography' || $trail[1]['path'] == 'people')$cond = true;
		}
		if($cond){
				$cr = array();
				$cr[] = '<a href="/villages/all">Деревни</a>'. $output;
				array_splice($crumbs, 1,0, $cr);
				$node = menu_get_object();
				if(!empty($node->field_category)){ 
				$cur_tid = $node->field_category['und'][0]['tid'];
				} else { 
					if(isset($trail[1]['menu_name'])){ 
						if(strpos($trail[1]['menu_name'], 'book-toc-') !== false){ 
							$bookarr = explode('-', $trail[1]['menu_name']);
							$bnid = $bookarr[2];
							$node = node_load($bnid);
							if(isset($node->field_category)){
							$cur_tid = $node->field_category['und'][0]['tid'];
						}
					}
				}
				}
				if(isset($cur_tid)){
					$current_term = taxonomy_term_load($cur_tid);
					$nids = taxonomy_select_nodes($current_term->tid);
						if(!empty($nids)) {
							$out = '<ul class="submenu sf-menu">';
						$nodes = node_load_multiple($nids);
							foreach($nodes as $node){
								$out .= '<li>'. l($node->title, drupal_get_path_alias('node/'. $node->nid)) . '</li>';				
							}
							$out .= '</ul>';
						}
						$cr = array();
						$cr[] = l($current_term->name, '/villages/' . drupal_get_path_alias('taxonomy/term/'. $cur_tid)) . $out;
						array_splice($crumbs, 2,0, $cr);
				}
		}
		//Add geo and people links
		$cr = array();
		$cr[] = l('География','/geography');
		$cr[] = l('Люди','/people');
		array_splice($crumbs, 1,0, $cr);
	return $crumbs;
}